-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity model_quantMul_8ul_8ul_1_7_6_s is
port (
    ap_ready : OUT STD_LOGIC;
    in1_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (6 downto 0) );
end;


architecture behav of model_quantMul_8ul_8ul_1_7_6_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv9_62 : STD_LOGIC_VECTOR (8 downto 0) := "001100010";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal mul_ln111_fu_22_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln111_fu_22_p2 : STD_LOGIC_VECTOR (8 downto 0);

    component model_mul_3s_8ns_9_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;



begin
    mul_3s_8ns_9_1_1_U1577 : component model_mul_3s_8ns_9_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 8,
        dout_WIDTH => 9)
    port map (
        din0 => in1_V_read,
        din1 => mul_ln111_fu_22_p1,
        dout => mul_ln111_fu_22_p2);




    ap_ready <= ap_const_logic_1;
    ap_return <= mul_ln111_fu_22_p2(8 downto 2);
    mul_ln111_fu_22_p1 <= ap_const_lv9_62(8 - 1 downto 0);
end behav;
