// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module model_quantMul_8ul_8ul_6_6_6_s (
        ap_ready,
        in1_V_read,
        in2_V_read,
        ap_return
);


output   ap_ready;
input  [7:0] in1_V_read;
input  [7:0] in2_V_read;
output  [7:0] ap_return;

wire   [13:0] mul_ln111_fu_32_p2;

model_mul_8s_8s_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 14 ))
mul_8s_8s_14_1_1_U2044(
    .din0(in2_V_read),
    .din1(in1_V_read),
    .dout(mul_ln111_fu_32_p2)
);

assign ap_ready = 1'b1;

assign ap_return = {{mul_ln111_fu_32_p2[13:6]}};

endmodule //model_quantMul_8ul_8ul_6_6_6_s
