// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module model_quantMul_8ul_8ul_1_7_6_s (
        ap_ready,
        in1_V_read,
        ap_return
);


output   ap_ready;
input  [2:0] in1_V_read;
output  [6:0] ap_return;

wire   [7:0] mul_ln111_fu_22_p1;
wire   [8:0] mul_ln111_fu_22_p2;

model_mul_3s_8ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 9 ))
mul_3s_8ns_9_1_1_U1577(
    .din0(in1_V_read),
    .din1(mul_ln111_fu_22_p1),
    .dout(mul_ln111_fu_22_p2)
);

assign ap_ready = 1'b1;

assign ap_return = {{mul_ln111_fu_22_p2[8:2]}};

assign mul_ln111_fu_22_p1 = 9'd98;

endmodule //model_quantMul_8ul_8ul_1_7_6_s
