// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module model_evaluate_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inputs_address0,
        inputs_ce0,
        inputs_q0,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] inputs_address0;
output   inputs_ce0;
input  [7:0] inputs_q0;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;
output  [7:0] ap_return_7;
output  [7:0] ap_return_8;
output  [7:0] ap_return_9;
output  [7:0] ap_return_10;
output  [7:0] ap_return_11;
output  [7:0] ap_return_12;
output  [7:0] ap_return_13;
output  [7:0] ap_return_14;
output  [7:0] ap_return_15;
output  [7:0] ap_return_16;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_start;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_done;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_idle;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_ready;
wire   [5:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_inputs_address0;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_inputs_ce0;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1624_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1624_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1523_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1523_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1422_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1422_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1321_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1321_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1220_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1220_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1119_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1119_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1018_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1018_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_917_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_917_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_816_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_816_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_715_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_715_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_614_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_614_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_513_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_513_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_412_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_412_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_311_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_311_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_210_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_210_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_19_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_19_out_ap_vld;
wire   [20:0] grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i8_out;
wire    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i8_out_ap_vld;
reg    grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [20:0] biasedSum_fu_208_p2;
wire   [5:0] tmp_fu_224_p4;
wire   [12:0] trunc_ln_fu_214_p4;
wire   [0:0] icmp_ln1035_fu_234_p2;
wire   [0:0] icmp_ln1027_fu_240_p2;
wire   [0:0] or_ln154_fu_264_p2;
wire   [7:0] select_ln154_fu_256_p3;
wire   [7:0] result_V_fu_246_p4;
wire   [20:0] biasedSum_1_fu_278_p2;
wire   [5:0] tmp_1_fu_294_p4;
wire   [12:0] trunc_ln1669_s_fu_284_p4;
wire   [0:0] icmp_ln1035_1_fu_304_p2;
wire   [0:0] icmp_ln1027_1_fu_310_p2;
wire   [0:0] or_ln154_1_fu_334_p2;
wire   [7:0] select_ln154_2_fu_326_p3;
wire   [7:0] result_V_2_fu_316_p4;
wire   [20:0] biasedSum_2_fu_348_p2;
wire   [5:0] tmp_2_fu_364_p4;
wire   [12:0] trunc_ln1669_1_fu_354_p4;
wire   [0:0] icmp_ln1035_2_fu_374_p2;
wire   [0:0] icmp_ln1027_2_fu_380_p2;
wire   [0:0] or_ln154_2_fu_404_p2;
wire   [7:0] select_ln154_4_fu_396_p3;
wire   [7:0] result_V_4_fu_386_p4;
wire   [20:0] biasedSum_3_fu_418_p2;
wire   [5:0] tmp_3_fu_434_p4;
wire   [12:0] trunc_ln1669_2_fu_424_p4;
wire   [0:0] icmp_ln1035_3_fu_444_p2;
wire   [0:0] icmp_ln1027_3_fu_450_p2;
wire   [0:0] or_ln154_3_fu_474_p2;
wire   [7:0] select_ln154_6_fu_466_p3;
wire   [7:0] result_V_6_fu_456_p4;
wire   [20:0] biasedSum_4_fu_488_p2;
wire   [5:0] tmp_4_fu_504_p4;
wire   [12:0] trunc_ln1669_3_fu_494_p4;
wire   [0:0] icmp_ln1035_4_fu_514_p2;
wire   [0:0] icmp_ln1027_4_fu_520_p2;
wire   [0:0] or_ln154_4_fu_544_p2;
wire   [7:0] select_ln154_8_fu_536_p3;
wire   [7:0] result_V_8_fu_526_p4;
wire   [20:0] biasedSum_5_fu_558_p2;
wire   [5:0] tmp_5_fu_574_p4;
wire   [12:0] trunc_ln1669_4_fu_564_p4;
wire   [0:0] icmp_ln1035_5_fu_584_p2;
wire   [0:0] icmp_ln1027_5_fu_590_p2;
wire   [0:0] or_ln154_5_fu_614_p2;
wire   [7:0] select_ln154_10_fu_606_p3;
wire   [7:0] result_V_10_fu_596_p4;
wire   [20:0] biasedSum_6_fu_628_p2;
wire   [5:0] tmp_6_fu_644_p4;
wire   [12:0] trunc_ln1669_5_fu_634_p4;
wire   [0:0] icmp_ln1035_6_fu_654_p2;
wire   [0:0] icmp_ln1027_6_fu_660_p2;
wire   [0:0] or_ln154_6_fu_684_p2;
wire   [7:0] select_ln154_12_fu_676_p3;
wire   [7:0] result_V_12_fu_666_p4;
wire   [20:0] biasedSum_7_fu_698_p2;
wire   [5:0] tmp_7_fu_714_p4;
wire   [12:0] trunc_ln1669_6_fu_704_p4;
wire   [0:0] icmp_ln1035_7_fu_724_p2;
wire   [0:0] icmp_ln1027_7_fu_730_p2;
wire   [0:0] or_ln154_7_fu_754_p2;
wire   [7:0] select_ln154_14_fu_746_p3;
wire   [7:0] result_V_14_fu_736_p4;
wire   [20:0] biasedSum_8_fu_768_p2;
wire   [5:0] tmp_8_fu_784_p4;
wire   [12:0] trunc_ln1669_7_fu_774_p4;
wire   [0:0] icmp_ln1035_8_fu_794_p2;
wire   [0:0] icmp_ln1027_8_fu_800_p2;
wire   [0:0] or_ln154_8_fu_824_p2;
wire   [7:0] select_ln154_16_fu_816_p3;
wire   [7:0] result_V_16_fu_806_p4;
wire   [20:0] biasedSum_9_fu_838_p2;
wire   [5:0] tmp_9_fu_854_p4;
wire   [12:0] trunc_ln1669_8_fu_844_p4;
wire   [0:0] icmp_ln1035_9_fu_864_p2;
wire   [0:0] icmp_ln1027_9_fu_870_p2;
wire   [0:0] or_ln154_9_fu_894_p2;
wire   [7:0] select_ln154_18_fu_886_p3;
wire   [7:0] result_V_18_fu_876_p4;
wire   [20:0] biasedSum_10_fu_908_p2;
wire   [5:0] tmp_10_fu_924_p4;
wire   [12:0] trunc_ln1669_9_fu_914_p4;
wire   [0:0] icmp_ln1035_10_fu_934_p2;
wire   [0:0] icmp_ln1027_10_fu_940_p2;
wire   [0:0] or_ln154_10_fu_964_p2;
wire   [7:0] select_ln154_20_fu_956_p3;
wire   [7:0] result_V_20_fu_946_p4;
wire   [20:0] biasedSum_11_fu_978_p2;
wire   [5:0] tmp_11_fu_994_p4;
wire   [12:0] trunc_ln1669_10_fu_984_p4;
wire   [0:0] icmp_ln1035_11_fu_1004_p2;
wire   [0:0] icmp_ln1027_11_fu_1010_p2;
wire   [0:0] or_ln154_11_fu_1034_p2;
wire   [7:0] select_ln154_22_fu_1026_p3;
wire   [7:0] result_V_22_fu_1016_p4;
wire   [20:0] biasedSum_12_fu_1048_p2;
wire   [5:0] tmp_12_fu_1064_p4;
wire   [12:0] trunc_ln1669_11_fu_1054_p4;
wire   [0:0] icmp_ln1035_12_fu_1074_p2;
wire   [0:0] icmp_ln1027_12_fu_1080_p2;
wire   [0:0] or_ln154_12_fu_1104_p2;
wire   [7:0] select_ln154_24_fu_1096_p3;
wire   [7:0] result_V_24_fu_1086_p4;
wire   [20:0] biasedSum_13_fu_1118_p2;
wire   [5:0] tmp_13_fu_1134_p4;
wire   [12:0] trunc_ln1669_12_fu_1124_p4;
wire   [0:0] icmp_ln1035_13_fu_1144_p2;
wire   [0:0] icmp_ln1027_13_fu_1150_p2;
wire   [0:0] or_ln154_13_fu_1174_p2;
wire   [7:0] select_ln154_26_fu_1166_p3;
wire   [7:0] result_V_26_fu_1156_p4;
wire   [20:0] biasedSum_14_fu_1188_p2;
wire   [5:0] tmp_14_fu_1204_p4;
wire   [12:0] trunc_ln1669_13_fu_1194_p4;
wire   [0:0] icmp_ln1035_14_fu_1214_p2;
wire   [0:0] icmp_ln1027_14_fu_1220_p2;
wire   [0:0] or_ln154_14_fu_1244_p2;
wire   [7:0] select_ln154_28_fu_1236_p3;
wire   [7:0] result_V_28_fu_1226_p4;
wire   [20:0] biasedSum_15_fu_1258_p2;
wire   [5:0] tmp_15_fu_1274_p4;
wire   [12:0] trunc_ln1669_14_fu_1264_p4;
wire   [0:0] icmp_ln1035_15_fu_1284_p2;
wire   [0:0] icmp_ln1027_15_fu_1290_p2;
wire   [0:0] or_ln154_15_fu_1314_p2;
wire   [7:0] select_ln154_30_fu_1306_p3;
wire   [7:0] result_V_30_fu_1296_p4;
wire   [20:0] biasedSum_16_fu_1328_p2;
wire   [5:0] tmp_16_fu_1344_p4;
wire   [12:0] trunc_ln1669_15_fu_1334_p4;
wire   [0:0] icmp_ln1035_16_fu_1354_p2;
wire   [0:0] icmp_ln1027_16_fu_1360_p2;
wire   [0:0] or_ln154_16_fu_1384_p2;
wire   [7:0] select_ln154_32_fu_1376_p3;
wire   [7:0] result_V_32_fu_1366_p4;
wire   [7:0] result_V_1_fu_270_p3;
wire   [7:0] result_V_3_fu_340_p3;
wire   [7:0] result_V_5_fu_410_p3;
wire   [7:0] result_V_7_fu_480_p3;
wire   [7:0] result_V_9_fu_550_p3;
wire   [7:0] result_V_11_fu_620_p3;
wire   [7:0] result_V_13_fu_690_p3;
wire   [7:0] result_V_15_fu_760_p3;
wire   [7:0] result_V_17_fu_830_p3;
wire   [7:0] result_V_19_fu_900_p3;
wire   [7:0] result_V_21_fu_970_p3;
wire   [7:0] result_V_23_fu_1040_p3;
wire   [7:0] result_V_25_fu_1110_p3;
wire   [7:0] result_V_27_fu_1180_p3;
wire   [7:0] result_V_29_fu_1250_p3;
wire   [7:0] result_V_31_fu_1320_p3;
wire   [7:0] result_V_33_fu_1390_p3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_start_reg = 1'b0;
end

model_evaluate_7_Pipeline_VITIS_LOOP_122_2 grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_start),
    .ap_done(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_done),
    .ap_idle(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_idle),
    .ap_ready(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_ready),
    .inputs_address0(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_inputs_address0),
    .inputs_ce0(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_inputs_ce0),
    .inputs_q0(inputs_q0),
    .conv4_i_1624_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1624_out),
    .conv4_i_1624_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1624_out_ap_vld),
    .conv4_i_1523_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1523_out),
    .conv4_i_1523_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1523_out_ap_vld),
    .conv4_i_1422_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1422_out),
    .conv4_i_1422_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1422_out_ap_vld),
    .conv4_i_1321_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1321_out),
    .conv4_i_1321_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1321_out_ap_vld),
    .conv4_i_1220_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1220_out),
    .conv4_i_1220_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1220_out_ap_vld),
    .conv4_i_1119_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1119_out),
    .conv4_i_1119_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1119_out_ap_vld),
    .conv4_i_1018_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1018_out),
    .conv4_i_1018_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1018_out_ap_vld),
    .conv4_i_917_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_917_out),
    .conv4_i_917_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_917_out_ap_vld),
    .conv4_i_816_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_816_out),
    .conv4_i_816_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_816_out_ap_vld),
    .conv4_i_715_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_715_out),
    .conv4_i_715_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_715_out_ap_vld),
    .conv4_i_614_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_614_out),
    .conv4_i_614_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_614_out_ap_vld),
    .conv4_i_513_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_513_out),
    .conv4_i_513_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_513_out_ap_vld),
    .conv4_i_412_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_412_out),
    .conv4_i_412_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_412_out_ap_vld),
    .conv4_i_311_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_311_out),
    .conv4_i_311_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_311_out_ap_vld),
    .conv4_i_210_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_210_out),
    .conv4_i_210_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_210_out_ap_vld),
    .conv4_i_19_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_19_out),
    .conv4_i_19_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_19_out_ap_vld),
    .conv4_i8_out(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i8_out),
    .conv4_i8_out_ap_vld(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i8_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_start_reg <= 1'b1;
        end else if ((grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_ready == 1'b1)) begin
            grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_return_0 = result_V_1_fu_270_p3;

assign ap_return_1 = result_V_3_fu_340_p3;

assign ap_return_10 = result_V_21_fu_970_p3;

assign ap_return_11 = result_V_23_fu_1040_p3;

assign ap_return_12 = result_V_25_fu_1110_p3;

assign ap_return_13 = result_V_27_fu_1180_p3;

assign ap_return_14 = result_V_29_fu_1250_p3;

assign ap_return_15 = result_V_31_fu_1320_p3;

assign ap_return_16 = result_V_33_fu_1390_p3;

assign ap_return_2 = result_V_5_fu_410_p3;

assign ap_return_3 = result_V_7_fu_480_p3;

assign ap_return_4 = result_V_9_fu_550_p3;

assign ap_return_5 = result_V_11_fu_620_p3;

assign ap_return_6 = result_V_13_fu_690_p3;

assign ap_return_7 = result_V_15_fu_760_p3;

assign ap_return_8 = result_V_17_fu_830_p3;

assign ap_return_9 = result_V_19_fu_900_p3;

assign biasedSum_10_fu_908_p2 = ($signed(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1018_out) + $signed(21'd2097040));

assign biasedSum_11_fu_978_p2 = (grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1119_out + 21'd160);

assign biasedSum_12_fu_1048_p2 = (grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1220_out + 21'd80);

assign biasedSum_13_fu_1118_p2 = (grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1321_out + 21'd128);

assign biasedSum_14_fu_1188_p2 = (grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1422_out + 21'd64);

assign biasedSum_15_fu_1258_p2 = (grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1523_out + 21'd112);

assign biasedSum_16_fu_1328_p2 = ($signed(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_1624_out) + $signed(21'd2096992));

assign biasedSum_1_fu_278_p2 = ($signed(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_19_out) + $signed(21'd2097008));

assign biasedSum_2_fu_348_p2 = ($signed(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_210_out) + $signed(21'd2096752));

assign biasedSum_3_fu_418_p2 = ($signed(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_311_out) + $signed(21'd2097072));

assign biasedSum_4_fu_488_p2 = (grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_412_out + 21'd336);

assign biasedSum_5_fu_558_p2 = ($signed(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_513_out) + $signed(21'd2096944));

assign biasedSum_6_fu_628_p2 = ($signed(grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_614_out) + $signed(21'd2096608));

assign biasedSum_7_fu_698_p2 = (grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_715_out + 21'd480);

assign biasedSum_8_fu_768_p2 = (grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_816_out + 21'd1616);

assign biasedSum_9_fu_838_p2 = (grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i_917_out + 21'd192);

assign biasedSum_fu_208_p2 = (grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_conv4_i8_out + 21'd1792);

assign grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_start = grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_ap_start_reg;

assign icmp_ln1027_10_fu_940_p2 = (($signed(trunc_ln1669_9_fu_914_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_11_fu_1010_p2 = (($signed(trunc_ln1669_10_fu_984_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_12_fu_1080_p2 = (($signed(trunc_ln1669_11_fu_1054_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_13_fu_1150_p2 = (($signed(trunc_ln1669_12_fu_1124_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_14_fu_1220_p2 = (($signed(trunc_ln1669_13_fu_1194_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_15_fu_1290_p2 = (($signed(trunc_ln1669_14_fu_1264_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_16_fu_1360_p2 = (($signed(trunc_ln1669_15_fu_1334_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_1_fu_310_p2 = (($signed(trunc_ln1669_s_fu_284_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_2_fu_380_p2 = (($signed(trunc_ln1669_1_fu_354_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_3_fu_450_p2 = (($signed(trunc_ln1669_2_fu_424_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_4_fu_520_p2 = (($signed(trunc_ln1669_3_fu_494_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_5_fu_590_p2 = (($signed(trunc_ln1669_4_fu_564_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_6_fu_660_p2 = (($signed(trunc_ln1669_5_fu_634_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_7_fu_730_p2 = (($signed(trunc_ln1669_6_fu_704_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_8_fu_800_p2 = (($signed(trunc_ln1669_7_fu_774_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_9_fu_870_p2 = (($signed(trunc_ln1669_8_fu_844_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_240_p2 = (($signed(trunc_ln_fu_214_p4) < $signed(13'd8065)) ? 1'b1 : 1'b0);

assign icmp_ln1035_10_fu_934_p2 = (($signed(tmp_10_fu_924_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_11_fu_1004_p2 = (($signed(tmp_11_fu_994_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_12_fu_1074_p2 = (($signed(tmp_12_fu_1064_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_13_fu_1144_p2 = (($signed(tmp_13_fu_1134_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_14_fu_1214_p2 = (($signed(tmp_14_fu_1204_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_15_fu_1284_p2 = (($signed(tmp_15_fu_1274_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_16_fu_1354_p2 = (($signed(tmp_16_fu_1344_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_1_fu_304_p2 = (($signed(tmp_1_fu_294_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_2_fu_374_p2 = (($signed(tmp_2_fu_364_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_3_fu_444_p2 = (($signed(tmp_3_fu_434_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_4_fu_514_p2 = (($signed(tmp_4_fu_504_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_5_fu_584_p2 = (($signed(tmp_5_fu_574_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_6_fu_654_p2 = (($signed(tmp_6_fu_644_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_7_fu_724_p2 = (($signed(tmp_7_fu_714_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_8_fu_794_p2 = (($signed(tmp_8_fu_784_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_9_fu_864_p2 = (($signed(tmp_9_fu_854_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_234_p2 = (($signed(tmp_fu_224_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign inputs_address0 = grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_inputs_address0;

assign inputs_ce0 = grp_evaluate_7_Pipeline_VITIS_LOOP_122_2_fu_132_inputs_ce0;

assign or_ln154_10_fu_964_p2 = (icmp_ln1035_10_fu_934_p2 | icmp_ln1027_10_fu_940_p2);

assign or_ln154_11_fu_1034_p2 = (icmp_ln1035_11_fu_1004_p2 | icmp_ln1027_11_fu_1010_p2);

assign or_ln154_12_fu_1104_p2 = (icmp_ln1035_12_fu_1074_p2 | icmp_ln1027_12_fu_1080_p2);

assign or_ln154_13_fu_1174_p2 = (icmp_ln1035_13_fu_1144_p2 | icmp_ln1027_13_fu_1150_p2);

assign or_ln154_14_fu_1244_p2 = (icmp_ln1035_14_fu_1214_p2 | icmp_ln1027_14_fu_1220_p2);

assign or_ln154_15_fu_1314_p2 = (icmp_ln1035_15_fu_1284_p2 | icmp_ln1027_15_fu_1290_p2);

assign or_ln154_16_fu_1384_p2 = (icmp_ln1035_16_fu_1354_p2 | icmp_ln1027_16_fu_1360_p2);

assign or_ln154_1_fu_334_p2 = (icmp_ln1035_1_fu_304_p2 | icmp_ln1027_1_fu_310_p2);

assign or_ln154_2_fu_404_p2 = (icmp_ln1035_2_fu_374_p2 | icmp_ln1027_2_fu_380_p2);

assign or_ln154_3_fu_474_p2 = (icmp_ln1035_3_fu_444_p2 | icmp_ln1027_3_fu_450_p2);

assign or_ln154_4_fu_544_p2 = (icmp_ln1035_4_fu_514_p2 | icmp_ln1027_4_fu_520_p2);

assign or_ln154_5_fu_614_p2 = (icmp_ln1035_5_fu_584_p2 | icmp_ln1027_5_fu_590_p2);

assign or_ln154_6_fu_684_p2 = (icmp_ln1035_6_fu_654_p2 | icmp_ln1027_6_fu_660_p2);

assign or_ln154_7_fu_754_p2 = (icmp_ln1035_7_fu_724_p2 | icmp_ln1027_7_fu_730_p2);

assign or_ln154_8_fu_824_p2 = (icmp_ln1035_8_fu_794_p2 | icmp_ln1027_8_fu_800_p2);

assign or_ln154_9_fu_894_p2 = (icmp_ln1035_9_fu_864_p2 | icmp_ln1027_9_fu_870_p2);

assign or_ln154_fu_264_p2 = (icmp_ln1035_fu_234_p2 | icmp_ln1027_fu_240_p2);

assign result_V_10_fu_596_p4 = {{biasedSum_5_fu_558_p2[15:8]}};

assign result_V_11_fu_620_p3 = ((or_ln154_5_fu_614_p2[0:0] == 1'b1) ? select_ln154_10_fu_606_p3 : result_V_10_fu_596_p4);

assign result_V_12_fu_666_p4 = {{biasedSum_6_fu_628_p2[15:8]}};

assign result_V_13_fu_690_p3 = ((or_ln154_6_fu_684_p2[0:0] == 1'b1) ? select_ln154_12_fu_676_p3 : result_V_12_fu_666_p4);

assign result_V_14_fu_736_p4 = {{biasedSum_7_fu_698_p2[15:8]}};

assign result_V_15_fu_760_p3 = ((or_ln154_7_fu_754_p2[0:0] == 1'b1) ? select_ln154_14_fu_746_p3 : result_V_14_fu_736_p4);

assign result_V_16_fu_806_p4 = {{biasedSum_8_fu_768_p2[15:8]}};

assign result_V_17_fu_830_p3 = ((or_ln154_8_fu_824_p2[0:0] == 1'b1) ? select_ln154_16_fu_816_p3 : result_V_16_fu_806_p4);

assign result_V_18_fu_876_p4 = {{biasedSum_9_fu_838_p2[15:8]}};

assign result_V_19_fu_900_p3 = ((or_ln154_9_fu_894_p2[0:0] == 1'b1) ? select_ln154_18_fu_886_p3 : result_V_18_fu_876_p4);

assign result_V_1_fu_270_p3 = ((or_ln154_fu_264_p2[0:0] == 1'b1) ? select_ln154_fu_256_p3 : result_V_fu_246_p4);

assign result_V_20_fu_946_p4 = {{biasedSum_10_fu_908_p2[15:8]}};

assign result_V_21_fu_970_p3 = ((or_ln154_10_fu_964_p2[0:0] == 1'b1) ? select_ln154_20_fu_956_p3 : result_V_20_fu_946_p4);

assign result_V_22_fu_1016_p4 = {{biasedSum_11_fu_978_p2[15:8]}};

assign result_V_23_fu_1040_p3 = ((or_ln154_11_fu_1034_p2[0:0] == 1'b1) ? select_ln154_22_fu_1026_p3 : result_V_22_fu_1016_p4);

assign result_V_24_fu_1086_p4 = {{biasedSum_12_fu_1048_p2[15:8]}};

assign result_V_25_fu_1110_p3 = ((or_ln154_12_fu_1104_p2[0:0] == 1'b1) ? select_ln154_24_fu_1096_p3 : result_V_24_fu_1086_p4);

assign result_V_26_fu_1156_p4 = {{biasedSum_13_fu_1118_p2[15:8]}};

assign result_V_27_fu_1180_p3 = ((or_ln154_13_fu_1174_p2[0:0] == 1'b1) ? select_ln154_26_fu_1166_p3 : result_V_26_fu_1156_p4);

assign result_V_28_fu_1226_p4 = {{biasedSum_14_fu_1188_p2[15:8]}};

assign result_V_29_fu_1250_p3 = ((or_ln154_14_fu_1244_p2[0:0] == 1'b1) ? select_ln154_28_fu_1236_p3 : result_V_28_fu_1226_p4);

assign result_V_2_fu_316_p4 = {{biasedSum_1_fu_278_p2[15:8]}};

assign result_V_30_fu_1296_p4 = {{biasedSum_15_fu_1258_p2[15:8]}};

assign result_V_31_fu_1320_p3 = ((or_ln154_15_fu_1314_p2[0:0] == 1'b1) ? select_ln154_30_fu_1306_p3 : result_V_30_fu_1296_p4);

assign result_V_32_fu_1366_p4 = {{biasedSum_16_fu_1328_p2[15:8]}};

assign result_V_33_fu_1390_p3 = ((or_ln154_16_fu_1384_p2[0:0] == 1'b1) ? select_ln154_32_fu_1376_p3 : result_V_32_fu_1366_p4);

assign result_V_3_fu_340_p3 = ((or_ln154_1_fu_334_p2[0:0] == 1'b1) ? select_ln154_2_fu_326_p3 : result_V_2_fu_316_p4);

assign result_V_4_fu_386_p4 = {{biasedSum_2_fu_348_p2[15:8]}};

assign result_V_5_fu_410_p3 = ((or_ln154_2_fu_404_p2[0:0] == 1'b1) ? select_ln154_4_fu_396_p3 : result_V_4_fu_386_p4);

assign result_V_6_fu_456_p4 = {{biasedSum_3_fu_418_p2[15:8]}};

assign result_V_7_fu_480_p3 = ((or_ln154_3_fu_474_p2[0:0] == 1'b1) ? select_ln154_6_fu_466_p3 : result_V_6_fu_456_p4);

assign result_V_8_fu_526_p4 = {{biasedSum_4_fu_488_p2[15:8]}};

assign result_V_9_fu_550_p3 = ((or_ln154_4_fu_544_p2[0:0] == 1'b1) ? select_ln154_8_fu_536_p3 : result_V_8_fu_526_p4);

assign result_V_fu_246_p4 = {{biasedSum_fu_208_p2[15:8]}};

assign select_ln154_10_fu_606_p3 = ((icmp_ln1035_5_fu_584_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_12_fu_676_p3 = ((icmp_ln1035_6_fu_654_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_14_fu_746_p3 = ((icmp_ln1035_7_fu_724_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_16_fu_816_p3 = ((icmp_ln1035_8_fu_794_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_18_fu_886_p3 = ((icmp_ln1035_9_fu_864_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_20_fu_956_p3 = ((icmp_ln1035_10_fu_934_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_22_fu_1026_p3 = ((icmp_ln1035_11_fu_1004_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_24_fu_1096_p3 = ((icmp_ln1035_12_fu_1074_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_26_fu_1166_p3 = ((icmp_ln1035_13_fu_1144_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_28_fu_1236_p3 = ((icmp_ln1035_14_fu_1214_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_2_fu_326_p3 = ((icmp_ln1035_1_fu_304_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_30_fu_1306_p3 = ((icmp_ln1035_15_fu_1284_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_32_fu_1376_p3 = ((icmp_ln1035_16_fu_1354_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_4_fu_396_p3 = ((icmp_ln1035_2_fu_374_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_6_fu_466_p3 = ((icmp_ln1035_3_fu_444_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_8_fu_536_p3 = ((icmp_ln1035_4_fu_514_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign select_ln154_fu_256_p3 = ((icmp_ln1035_fu_234_p2[0:0] == 1'b1) ? 8'd127 : 8'd129);

assign tmp_10_fu_924_p4 = {{biasedSum_10_fu_908_p2[20:15]}};

assign tmp_11_fu_994_p4 = {{biasedSum_11_fu_978_p2[20:15]}};

assign tmp_12_fu_1064_p4 = {{biasedSum_12_fu_1048_p2[20:15]}};

assign tmp_13_fu_1134_p4 = {{biasedSum_13_fu_1118_p2[20:15]}};

assign tmp_14_fu_1204_p4 = {{biasedSum_14_fu_1188_p2[20:15]}};

assign tmp_15_fu_1274_p4 = {{biasedSum_15_fu_1258_p2[20:15]}};

assign tmp_16_fu_1344_p4 = {{biasedSum_16_fu_1328_p2[20:15]}};

assign tmp_1_fu_294_p4 = {{biasedSum_1_fu_278_p2[20:15]}};

assign tmp_2_fu_364_p4 = {{biasedSum_2_fu_348_p2[20:15]}};

assign tmp_3_fu_434_p4 = {{biasedSum_3_fu_418_p2[20:15]}};

assign tmp_4_fu_504_p4 = {{biasedSum_4_fu_488_p2[20:15]}};

assign tmp_5_fu_574_p4 = {{biasedSum_5_fu_558_p2[20:15]}};

assign tmp_6_fu_644_p4 = {{biasedSum_6_fu_628_p2[20:15]}};

assign tmp_7_fu_714_p4 = {{biasedSum_7_fu_698_p2[20:15]}};

assign tmp_8_fu_784_p4 = {{biasedSum_8_fu_768_p2[20:15]}};

assign tmp_9_fu_854_p4 = {{biasedSum_9_fu_838_p2[20:15]}};

assign tmp_fu_224_p4 = {{biasedSum_fu_208_p2[20:15]}};

assign trunc_ln1669_10_fu_984_p4 = {{biasedSum_11_fu_978_p2[20:8]}};

assign trunc_ln1669_11_fu_1054_p4 = {{biasedSum_12_fu_1048_p2[20:8]}};

assign trunc_ln1669_12_fu_1124_p4 = {{biasedSum_13_fu_1118_p2[20:8]}};

assign trunc_ln1669_13_fu_1194_p4 = {{biasedSum_14_fu_1188_p2[20:8]}};

assign trunc_ln1669_14_fu_1264_p4 = {{biasedSum_15_fu_1258_p2[20:8]}};

assign trunc_ln1669_15_fu_1334_p4 = {{biasedSum_16_fu_1328_p2[20:8]}};

assign trunc_ln1669_1_fu_354_p4 = {{biasedSum_2_fu_348_p2[20:8]}};

assign trunc_ln1669_2_fu_424_p4 = {{biasedSum_3_fu_418_p2[20:8]}};

assign trunc_ln1669_3_fu_494_p4 = {{biasedSum_4_fu_488_p2[20:8]}};

assign trunc_ln1669_4_fu_564_p4 = {{biasedSum_5_fu_558_p2[20:8]}};

assign trunc_ln1669_5_fu_634_p4 = {{biasedSum_6_fu_628_p2[20:8]}};

assign trunc_ln1669_6_fu_704_p4 = {{biasedSum_7_fu_698_p2[20:8]}};

assign trunc_ln1669_7_fu_774_p4 = {{biasedSum_8_fu_768_p2[20:8]}};

assign trunc_ln1669_8_fu_844_p4 = {{biasedSum_9_fu_838_p2[20:8]}};

assign trunc_ln1669_9_fu_914_p4 = {{biasedSum_10_fu_908_p2[20:8]}};

assign trunc_ln1669_s_fu_284_p4 = {{biasedSum_1_fu_278_p2[20:8]}};

assign trunc_ln_fu_214_p4 = {{biasedSum_fu_208_p2[20:8]}};

endmodule //model_evaluate_7
